name = "Define"
uuid = "57380313-1b0e-4ca3-b95f-f2d0dc171e6e"
authors = ["Amin Yahyaabadi"]
version = "0.1.0"

[deps]
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
